### ISSUE TITLE
Remove plugin-autoupdate-filter from gitignore

### ISSUE THREAD

**Issue by jessLundie** [a8cteam51/team51-project-scaffold#1]
### Description

We need to remove `plugins/plugin-autoupdate-filter` from .gitignore

This line should go away:
https://github.com/a8cteam51/team51-project-scaffold/blob/fb8a6a0b91d3c4f37ae114e0ed4c974984ba595d/.gitignore#L13

Why? Because we don't want to track this plugin in GH. It now autoupdates itself on-site like a normal plugin.

**Comment by otakupahp** [comment]
This plugin should be on MU folder, right?

**Comment by jessLundie** [comment]
@otakupahp - No, generally we have this loading as a regular plugin so that it can be easily deactivated by a site admin as needed.

**Comment by ahegyes** [comment]
This is done @jessLundie 😄 I'm marking this as closed!
