### ISSUE TITLE
Explore whether it would be worth adding GH Actions for CSS/JS linting

### ISSUE THREAD

**Issue by ahegyes** [a8cteam51/team51-project-scaffold#13]
### Description

Similar to how we have actions to lint the PHP code, see if we should add actions to lint the CSS/JS code using the `lint` scripts in `package.json`

### Additional context

p6q8Tx-3ei-p2#comment-7925

**Comment by ahegyes** [comment]
Fixed by @Ninodevo in #14!

**Comment by Ninodevo** [comment]
Nice! I forgot that I had this PR open 😁
