### ISSUE TITLE
Add rewrite args to CPT declaration

### ISSUE THREAD

**Issue by NickGreen** [a8cteam51/team51-project-scaffold#18]
### Description

Consider adding rewrite args to the CPT declaration, so that admin changes of permalinks don't break CPT URLs.
e.g.
```PHP
'rewrite'            => array(
    'slug'       => 'my-custom-slug',
    'with_front' => false,
),
```

Those args are currently added here: https://github.com/a8cteam51/team51-project-scaffold/blob/trunk/mu-plugins/build-processes-demo-features/includes/custom-post-types.php#L31

### Additional context

More background on why this might be a good idea: p4Kr4c-cCf-p2

**Comment by ahegyes** [comment]
Closing as the issue was fixed in #19
