### ISSUE TITLE
Add automatic block loader

### ISSUE THREAD

**Issue by otakupahp** [a8cteam51/team51-project-scaffold#21]
### Description

As themes become more complex, is easy to forget to register blocks manually each time. 

Currently, the code requires to registrer blocks manually

https://github.com/a8cteam51/team51-project-scaffold/blob/4ec837408ebf7012fc854c049dcd8f852ae9f56d/mu-plugins/build-processes-demo-blocks/includes/plugin-setup.php#L15

### Additional context

On a different PR, @chrisbellboy improved the function to load them automatically as is done with the rest of files

https://github.com/a8cteam51/team51-project-scaffold/pull/5/files#diff-18bc00bc275ff0590d6e748a47ca53a991de52815417f1d06eab4eafd3e6b840

```
	$basename = basename( $block_dir );
		$callback = 'waw_blocks_render_block_' . str_replace( '-', '_', $basename );

		$args = array();
		if ( function_exists( $callback ) ) {
			$args['render_callback'] = $callback;
		}

		register_block_type( $block_dir, $args );
	}
```

it would be great to implement this

**Comment by ahegyes** [comment]
Closing this since blocks are now supposed to be added to the monorepo: https://github.com/a8cteam51/special-projects-blocks-monorepo
