### ISSUE TITLE
phpcs issues with functions.php

### ISSUE THREAD

**Issue by mdrovdahl** [a8cteam51/team51-project-scaffold#4]
Created a new site today using the team51-cli and was surprised to immediately receive an email regarding phpcs errors in the scaffold: 

https://github.com/a8cteam51/team51-project-scaffold/blob/c1f623b1667db50a5a100f39a504f2a8e5a445a5/themes/build-processes-demo/functions.php#L34-L35

```
----------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 34 | ERROR | [x] Expected 5 spaces after parameter type; 6 found
    |       |     (Squiz.Commenting.FunctionComment.SpacingAfterParamType)
 34 | ERROR | [x] Expected 9 spaces after parameter name; 13
    |       |     found
    |       |     (Squiz.Commenting.FunctionComment.SpacingAfterParamName)
 35 | ERROR | [x] Expected 1 spaces after parameter type; 2 found
    |       |     (Squiz.Commenting.FunctionComment.SpacingAfterParamType)
 35 | ERROR | [x] Expected 1 spaces after parameter name; 5 found
    |       |     (Squiz.Commenting.FunctionComment.SpacingAfterParamName)
----------------------------------------------------------------------
```

**Comment by mdrovdahl** [comment]
Since it's just a style matter, I'll defer to @ahegyes on editing or adding a phpcs ignore statement

**Comment by ahegyes** [comment]
Thanks for flagging this @mdrovdahl! We updated the global `phpcs` ruleset yesterday ([PR](https://github.com/a8cteam51/team51-configs/pull/1)) and forgot to check if the scaffolds are still holding up 😅 

Good to know that the global ruleset is working as intended though 😄

**Comment by ahegyes** [comment]
Forgot to write in my comment that I've fixed the scaffold repositories.
